"""Add justice violation and cp tables

Revision ID: 6704b1a70ac6
Revises: 92ddabb66c80
Create Date: 2025-12-01 11:07:10.188987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6704b1a70ac6'
down_revision: Union[str, None] = '92ddabb66c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('justice_cp_state',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cp_value', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_justice_cp_state_cp_value'), 'justice_cp_state', ['cp_value'], unique=False)
    op.create_table('justice_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('cp_delta', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_justice_violations_category'), 'justice_violations', ['category'], unique=False)
    op.create_index(op.f('ix_justice_violations_code'), 'justice_violations', ['code'], unique=False)
    op.create_index(op.f('ix_justice_violations_id'), 'justice_violations', ['id'], unique=False)
    op.create_index(op.f('ix_justice_violations_user_id'), 'justice_violations', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ton_wallet', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_performer', sa.Boolean(), nullable=False),
    sa.Column('is_agency_owner', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('telegram_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_token'), 'accounts', ['token'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('default_performer_share', sa.Integer(), nullable=False),
    sa.Column('default_agency_share', sa.Integer(), nullable=False),
    sa.Column('default_treasury_share', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
    op.create_index(op.f('ix_agencies_owner_user_id'), 'agencies', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_agencies_slug'), 'agencies', ['slug'], unique=True)
    op.create_table('citizen_scores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nova_credit', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('GHOST', 'GREY', 'SOLID', 'ELITE', 'LEGEND', name='credittier'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('total_positive_events', sa.Integer(), nullable=False),
    sa.Column('total_negative_events', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('positive_streak', sa.Integer(), nullable=False),
    sa.Column('negative_streak', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('last_positive_at', sa.DateTime(), nullable=True),
    sa.Column('last_negative_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_citizen_scores_user_id'), 'citizen_scores', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('type', sa.Enum('EARN', 'SPEND', 'TRANSFER', 'RAKE', 'FEE', 'BURN', 'DEPOSIT', 'WITHDRAW', 'REWARD', name='ledgerentrytype'), nullable=False),
    sa.Column('source_app', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_agency_id'), 'ledger_entries', ['agency_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_performer_id'), 'ledger_entries', ['performer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_id'), 'ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_related_user_id'), 'ledger_entries', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_source_app'), 'ledger_entries', ['source_app'], unique=False)
    op.create_index(op.f('ix_ledger_entries_type'), 'ledger_entries', ['type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_app', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_flags_flag_type'), 'risk_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_risk_flags_user_id'), 'risk_flags', ['user_id'], unique=False)
    op.create_table('score_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_app', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('weight_applied', sa.Float(), nullable=False),
    sa.Column('base_delta', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_changes_category'), 'score_changes', ['category'], unique=False)
    op.create_index(op.f('ix_score_changes_event_id'), 'score_changes', ['event_id'], unique=False)
    op.create_index(op.f('ix_score_changes_event_type'), 'score_changes', ['event_type'], unique=False)
    op.create_index(op.f('ix_score_changes_source_app'), 'score_changes', ['source_app'], unique=False)
    op.create_index(op.f('ix_score_changes_user_id'), 'score_changes', ['user_id'], unique=False)
    op.create_table('user_loyalty',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'DIAMOND', name='loyaltytier'), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('vip_priority', sa.Integer(), nullable=False),
    sa.Column('ai_credits_bonus', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_app', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xp_total_after', sa.Integer(), nullable=True),
    sa.Column('level_after', sa.Integer(), nullable=True),
    sa.Column('tier_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_event_type'), 'xp_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_xp_events_source_app'), 'xp_events', ['source_app'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('agency_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PATRONICE', 'OPERATOR', 'MANAGER', 'VIEWER', name='operatorrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_share', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_operators_agency_id'), 'agency_operators', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agency_operators_user_id'), 'agency_operators', ['user_id'], unique=False)
    op.create_table('performers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('type', sa.Enum('HUMAN', 'AI', 'HYBRID', name='performertype'), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('share_performer', sa.Integer(), nullable=False),
    sa.Column('share_agency', sa.Integer(), nullable=False),
    sa.Column('share_treasury', sa.Integer(), nullable=False),
    sa.Column('ai_profile_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('total_earnings', sa.Integer(), nullable=False),
    sa.Column('total_shows', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performers_agency_id'), 'performers', ['agency_id'], unique=False)
    op.create_index(op.f('ix_performers_handle'), 'performers', ['handle'], unique=True)
    op.create_index(op.f('ix_performers_user_id'), 'performers', ['user_id'], unique=False)
    op.alter_column('consent_records', 'clauses_accepted',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_privacy_profiles', 'data_usage_policy',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_privacy_profiles', 'data_usage_policy',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('consent_records', 'clauses_accepted',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_performers_user_id'), table_name='performers')
    op.drop_index(op.f('ix_performers_handle'), table_name='performers')
    op.drop_index(op.f('ix_performers_agency_id'), table_name='performers')
    op.drop_table('performers')
    op.drop_index(op.f('ix_agency_operators_user_id'), table_name='agency_operators')
    op.drop_index(op.f('ix_agency_operators_agency_id'), table_name='agency_operators')
    op.drop_table('agency_operators')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_source_app'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_event_type'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_table('user_loyalty')
    op.drop_index(op.f('ix_score_changes_user_id'), table_name='score_changes')
    op.drop_index(op.f('ix_score_changes_source_app'), table_name='score_changes')
    op.drop_index(op.f('ix_score_changes_event_type'), table_name='score_changes')
    op.drop_index(op.f('ix_score_changes_event_id'), table_name='score_changes')
    op.drop_index(op.f('ix_score_changes_category'), table_name='score_changes')
    op.drop_table('score_changes')
    op.drop_index(op.f('ix_risk_flags_user_id'), table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_flag_type'), table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_source_app'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_related_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reference_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_performer_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_agency_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_citizen_scores_user_id'), table_name='citizen_scores')
    op.drop_table('citizen_scores')
    op.drop_index(op.f('ix_agencies_slug'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_owner_user_id'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_token'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_justice_violations_user_id'), table_name='justice_violations')
    op.drop_index(op.f('ix_justice_violations_id'), table_name='justice_violations')
    op.drop_index(op.f('ix_justice_violations_code'), table_name='justice_violations')
    op.drop_index(op.f('ix_justice_violations_category'), table_name='justice_violations')
    op.drop_table('justice_violations')
    op.drop_index(op.f('ix_justice_cp_state_cp_value'), table_name='justice_cp_state')
    op.drop_table('justice_cp_state')
    # ### end Alembic commands ###

