"""Add telegram task and submission tables

Revision ID: c3730d451b9d
Revises: de27694c7d94
Create Date: 2025-12-02 04:28:50.652877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3730d451b9d'
down_revision: Union[str, None] = 'de27694c7d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='taskdifficulty'), nullable=False),
    sa.Column('task_type', sa.Enum('ONCHAIN', 'SOCIAL', 'MICROTASK', 'QUIZ', 'STREAK', 'REFERRAL', name='tasktype'), nullable=False),
    sa.Column('proof_type', sa.Enum('NONE', 'SCREENSHOT', 'LINK', 'TEXT', 'QUIZ_ANSWER', 'ONCHAIN_TX', name='prooftype'), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_ncr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('streak_required', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='taskstatus'), nullable=False),
    sa.Column('max_completions_per_user', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_tasks_category'), 'telegram_tasks', ['category'], unique=False)
    op.create_index(op.f('ix_telegram_tasks_expires_at'), 'telegram_tasks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_tasks_status'), 'telegram_tasks', ['status'], unique=False)
    op.create_table('telegram_task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['telegram_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_user_task_assignment')
    )
    op.create_index('ix_task_assignments_user_active', 'telegram_task_assignments', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_telegram_task_assignments_expires_at'), 'telegram_task_assignments', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_task_assignments_is_active'), 'telegram_task_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_telegram_task_assignments_task_id'), 'telegram_task_assignments', ['task_id'], unique=False)
    op.create_index(op.f('ix_telegram_task_assignments_user_id'), 'telegram_task_assignments', ['user_id'], unique=False)
    op.create_table('telegram_task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proof', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proof_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REWARDED', name='submissionstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['telegram_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_user_task_submission')
    )
    op.create_index('ix_task_submissions_status', 'telegram_task_submissions', ['status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_telegram_task_submissions_external_id'), 'telegram_task_submissions', ['external_id'], unique=True)
    op.create_index(op.f('ix_telegram_task_submissions_status'), 'telegram_task_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_task_submissions_submitted_at'), 'telegram_task_submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_telegram_task_submissions_task_id'), 'telegram_task_submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_telegram_task_submissions_user_id'), 'telegram_task_submissions', ['user_id'], unique=False)
    op.create_table('telegram_referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('ncr_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_tx_id', sa.Integer(), nullable=True),
    sa.Column('xp_event_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_tx_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['xp_event_id'], ['xp_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referrer_user_id', 'referred_user_id', name='uq_referral_pair')
    )
    op.create_index('ix_referral_rewards_code', 'telegram_referral_rewards', ['referral_code', 'rewarded_at'], unique=False)
    op.create_index(op.f('ix_telegram_referral_rewards_referral_code'), 'telegram_referral_rewards', ['referral_code'], unique=False)
    op.create_index(op.f('ix_telegram_referral_rewards_referred_user_id'), 'telegram_referral_rewards', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_referral_rewards_referrer_user_id'), 'telegram_referral_rewards', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_referral_rewards_rewarded_at'), 'telegram_referral_rewards', ['rewarded_at'], unique=False)
    op.create_table('telegram_task_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('ncr_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_tx_id', sa.Integer(), nullable=True),
    sa.Column('xp_event_id', sa.Integer(), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['telegram_task_submissions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['telegram_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_tx_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['xp_event_id'], ['xp_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_task_rewards_rewarded_at'), 'telegram_task_rewards', ['rewarded_at'], unique=False)
    op.create_index(op.f('ix_telegram_task_rewards_submission_id'), 'telegram_task_rewards', ['submission_id'], unique=True)
    op.create_index(op.f('ix_telegram_task_rewards_task_id'), 'telegram_task_rewards', ['task_id'], unique=False)
    op.create_index(op.f('ix_telegram_task_rewards_user_id'), 'telegram_task_rewards', ['user_id'], unique=False)
    op.drop_index(op.f('ix_system_accounts_account_type'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_agency_id'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_wallet_account_id'), table_name='system_accounts')
    op.drop_table('system_accounts')
    op.drop_index(op.f('ix_telemetry_events_created_at'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_session_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_user_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_treasury_flows_agency_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_app'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_kind'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_performer_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_reference_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_ts'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_user_id'), table_name='treasury_flows')
    op.drop_table('treasury_flows')
    op.drop_index(op.f('ix_justice_policy_params_active'), table_name='justice_policy_params')
    op.drop_index(op.f('ix_justice_policy_params_version'), table_name='justice_policy_params')
    op.drop_table('justice_policy_params')
    op.drop_index(op.f('ix_justice_policy_change_log_created_at'), table_name='justice_policy_change_log')
    op.drop_index(op.f('ix_justice_policy_change_log_policy_version'), table_name='justice_policy_change_log')
    op.drop_table('justice_policy_change_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('justice_policy_change_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('onchain_tx', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('justice_policy_change_log_pkey'))
    )
    op.create_index(op.f('ix_justice_policy_change_log_policy_version'), 'justice_policy_change_log', ['policy_version'], unique=False)
    op.create_index(op.f('ix_justice_policy_change_log_created_at'), 'justice_policy_change_log', ['created_at'], unique=False)
    op.create_table('justice_policy_params',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decay_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_eko', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_com', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_sys', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_trust', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_soft_flag', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_probation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_restricted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_lockdown', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('onchain_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onchain_block', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('onchain_tx', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity_multiplier', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('justice_policy_params_pkey'))
    )
    op.create_index(op.f('ix_justice_policy_params_version'), 'justice_policy_params', ['version'], unique=False)
    op.create_index(op.f('ix_justice_policy_params_active'), 'justice_policy_params', ['active'], unique=False)
    op.create_table('treasury_flows',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('app', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('net_to_performer', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('growth_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('performer_pool_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('dev_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('burn_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('treasury_flows_agency_id_fkey')),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], name=op.f('treasury_flows_performer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('treasury_flows_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('treasury_flows_pkey'))
    )
    op.create_index(op.f('ix_treasury_flows_user_id'), 'treasury_flows', ['user_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_ts'), 'treasury_flows', ['ts'], unique=False)
    op.create_index(op.f('ix_treasury_flows_reference_id'), 'treasury_flows', ['reference_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_performer_id'), 'treasury_flows', ['performer_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_kind'), 'treasury_flows', ['kind'], unique=False)
    op.create_index(op.f('ix_treasury_flows_app'), 'treasury_flows', ['app'], unique=False)
    op.create_index(op.f('ix_treasury_flows_agency_id'), 'treasury_flows', ['agency_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_events_pkey'))
    )
    op.create_index(op.f('ix_telemetry_events_user_id'), 'telemetry_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_session_id'), 'telemetry_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event'), 'telemetry_events', ['event'], unique=False)
    op.create_index(op.f('ix_telemetry_events_created_at'), 'telemetry_events', ['created_at'], unique=False)
    op.create_table('system_accounts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_type', postgresql.ENUM('USER', 'PERFORMER', 'AGENCY_TREASURY', 'STATE_TREASURY', 'POOL_GROWTH', 'POOL_PERFORMER', 'POOL_DEV', 'POOL_BURN', name='systemaccounttype'), autoincrement=False, nullable=False),
    sa.Column('wallet_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('system_accounts_agency_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['accounts.id'], name=op.f('system_accounts_wallet_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_accounts_pkey'))
    )
    op.create_index(op.f('ix_system_accounts_wallet_account_id'), 'system_accounts', ['wallet_account_id'], unique=True)
    op.create_index(op.f('ix_system_accounts_agency_id'), 'system_accounts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_system_accounts_account_type'), 'system_accounts', ['account_type'], unique=False)
    op.drop_index(op.f('ix_telegram_task_rewards_user_id'), table_name='telegram_task_rewards')
    op.drop_index(op.f('ix_telegram_task_rewards_task_id'), table_name='telegram_task_rewards')
    op.drop_index(op.f('ix_telegram_task_rewards_submission_id'), table_name='telegram_task_rewards')
    op.drop_index(op.f('ix_telegram_task_rewards_rewarded_at'), table_name='telegram_task_rewards')
    op.drop_table('telegram_task_rewards')
    op.drop_index(op.f('ix_telegram_referral_rewards_rewarded_at'), table_name='telegram_referral_rewards')
    op.drop_index(op.f('ix_telegram_referral_rewards_referrer_user_id'), table_name='telegram_referral_rewards')
    op.drop_index(op.f('ix_telegram_referral_rewards_referred_user_id'), table_name='telegram_referral_rewards')
    op.drop_index(op.f('ix_telegram_referral_rewards_referral_code'), table_name='telegram_referral_rewards')
    op.drop_index('ix_referral_rewards_code', table_name='telegram_referral_rewards')
    op.drop_table('telegram_referral_rewards')
    op.drop_index(op.f('ix_telegram_task_submissions_user_id'), table_name='telegram_task_submissions')
    op.drop_index(op.f('ix_telegram_task_submissions_task_id'), table_name='telegram_task_submissions')
    op.drop_index(op.f('ix_telegram_task_submissions_submitted_at'), table_name='telegram_task_submissions')
    op.drop_index(op.f('ix_telegram_task_submissions_status'), table_name='telegram_task_submissions')
    op.drop_index(op.f('ix_telegram_task_submissions_external_id'), table_name='telegram_task_submissions')
    op.drop_index('ix_task_submissions_status', table_name='telegram_task_submissions')
    op.drop_table('telegram_task_submissions')
    op.drop_index(op.f('ix_telegram_task_assignments_user_id'), table_name='telegram_task_assignments')
    op.drop_index(op.f('ix_telegram_task_assignments_task_id'), table_name='telegram_task_assignments')
    op.drop_index(op.f('ix_telegram_task_assignments_is_active'), table_name='telegram_task_assignments')
    op.drop_index(op.f('ix_telegram_task_assignments_expires_at'), table_name='telegram_task_assignments')
    op.drop_index('ix_task_assignments_user_active', table_name='telegram_task_assignments')
    op.drop_table('telegram_task_assignments')
    op.drop_index(op.f('ix_telegram_tasks_status'), table_name='telegram_tasks')
    op.drop_index(op.f('ix_telegram_tasks_expires_at'), table_name='telegram_tasks')
    op.drop_index(op.f('ix_telegram_tasks_category'), table_name='telegram_tasks')
    op.drop_table('telegram_tasks')
    # ### end Alembic commands ###

