"""Add regime field to user_cp_state

Revision ID: a2656853d6cb
Revises: 6704b1a70ac6
Create Date: 2025-12-01 11:10:19.655755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2656853d6cb'
down_revision: Union[str, None] = '6704b1a70ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('justice_cp_state', sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_justice_cp_state_regime'), 'justice_cp_state', ['regime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_justice_cp_state_regime'), table_name='justice_cp_state')
    op.drop_column('justice_cp_state', 'regime')
    # ### end Alembic commands ###

