"""Add telegram event tables

Revision ID: a199b487ec78
Revises: c3730d451b9d
Create Date: 2025-12-02 04:34:03.658840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a199b487ec78'
down_revision: Union[str, None] = 'c3730d451b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sa.Enum('NASIP_FRIDAY', 'QUEST_WAR', 'SEASONAL', 'RITUAL', 'ONBOARDING', name='eventtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'FINISHED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('reward_multiplier_xp', sa.Float(), nullable=False),
    sa.Column('reward_multiplier_ncr', sa.Float(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('min_level_required', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_events_code'), 'telegram_events', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_events_ends_at'), 'telegram_events', ['ends_at'], unique=False)
    op.create_index(op.f('ix_telegram_events_event_type'), 'telegram_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_telegram_events_starts_at'), 'telegram_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_telegram_events_status'), 'telegram_events', ['status'], unique=False)
    op.create_table('telegram_event_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('total_xp_earned', sa.Integer(), nullable=False),
    sa.Column('total_ncr_earned', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['telegram_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participation')
    )
    op.create_index('ix_event_participations_score', 'telegram_event_participations', ['event_id', 'total_xp_earned', 'tasks_completed'], unique=False)
    op.create_index(op.f('ix_telegram_event_participations_event_id'), 'telegram_event_participations', ['event_id'], unique=False)
    op.create_index(op.f('ix_telegram_event_participations_joined_at'), 'telegram_event_participations', ['joined_at'], unique=False)
    op.create_index(op.f('ix_telegram_event_participations_rank'), 'telegram_event_participations', ['rank'], unique=False)
    op.create_index(op.f('ix_telegram_event_participations_total_xp_earned'), 'telegram_event_participations', ['total_xp_earned'], unique=False)
    op.create_index(op.f('ix_telegram_event_participations_user_id'), 'telegram_event_participations', ['user_id'], unique=False)
    op.create_table('telegram_event_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_multiplier_xp', sa.Float(), nullable=True),
    sa.Column('reward_multiplier_ncr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['telegram_events.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['telegram_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'task_id', name='uq_event_task')
    )
    op.create_index('ix_event_tasks_event', 'telegram_event_tasks', ['event_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_telegram_event_tasks_event_id'), 'telegram_event_tasks', ['event_id'], unique=False)
    op.create_index(op.f('ix_telegram_event_tasks_task_id'), 'telegram_event_tasks', ['task_id'], unique=False)
    op.create_table('telegram_event_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus_xp', sa.Integer(), nullable=False),
    sa.Column('bonus_ncr', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('wallet_tx_id', sa.Integer(), nullable=True),
    sa.Column('xp_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['telegram_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_tx_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['xp_event_id'], ['xp_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_reward')
    )
    op.create_index('ix_event_rewards_reason', 'telegram_event_rewards', ['event_id', 'reason'], unique=False)
    op.create_index(op.f('ix_telegram_event_rewards_created_at'), 'telegram_event_rewards', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_event_rewards_event_id'), 'telegram_event_rewards', ['event_id'], unique=False)
    op.create_index(op.f('ix_telegram_event_rewards_user_id'), 'telegram_event_rewards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_event_rewards_user_id'), table_name='telegram_event_rewards')
    op.drop_index(op.f('ix_telegram_event_rewards_event_id'), table_name='telegram_event_rewards')
    op.drop_index(op.f('ix_telegram_event_rewards_created_at'), table_name='telegram_event_rewards')
    op.drop_index('ix_event_rewards_reason', table_name='telegram_event_rewards')
    op.drop_table('telegram_event_rewards')
    op.drop_index(op.f('ix_telegram_event_tasks_task_id'), table_name='telegram_event_tasks')
    op.drop_index(op.f('ix_telegram_event_tasks_event_id'), table_name='telegram_event_tasks')
    op.drop_index('ix_event_tasks_event', table_name='telegram_event_tasks')
    op.drop_table('telegram_event_tasks')
    op.drop_index(op.f('ix_telegram_event_participations_user_id'), table_name='telegram_event_participations')
    op.drop_index(op.f('ix_telegram_event_participations_total_xp_earned'), table_name='telegram_event_participations')
    op.drop_index(op.f('ix_telegram_event_participations_rank'), table_name='telegram_event_participations')
    op.drop_index(op.f('ix_telegram_event_participations_joined_at'), table_name='telegram_event_participations')
    op.drop_index(op.f('ix_telegram_event_participations_event_id'), table_name='telegram_event_participations')
    op.drop_index('ix_event_participations_score', table_name='telegram_event_participations')
    op.drop_table('telegram_event_participations')
    op.drop_index(op.f('ix_telegram_events_status'), table_name='telegram_events')
    op.drop_index(op.f('ix_telegram_events_starts_at'), table_name='telegram_events')
    op.drop_index(op.f('ix_telegram_events_event_type'), table_name='telegram_events')
    op.drop_index(op.f('ix_telegram_events_ends_at'), table_name='telegram_events')
    op.drop_index(op.f('ix_telegram_events_code'), table_name='telegram_events')
    op.drop_table('telegram_events')
    # ### end Alembic commands ###
