"""add_ncr_market_state_table

Revision ID: c6bc6ed47388
Revises: b0e85b8c627c
Create Date: 2025-12-02 15:18:13.031597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6bc6ed47388'
down_revision: Union[str, None] = 'b0e85b8c627c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_accounts_account_type'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_agency_id'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_wallet_account_id'), table_name='system_accounts')
    op.drop_table('system_accounts')
    op.drop_index(op.f('ix_justice_policy_params_active'), table_name='justice_policy_params')
    op.drop_index(op.f('ix_justice_policy_params_version'), table_name='justice_policy_params')
    op.drop_table('justice_policy_params')
    op.drop_index(op.f('ix_justice_policy_change_log_created_at'), table_name='justice_policy_change_log')
    op.drop_index(op.f('ix_justice_policy_change_log_policy_version'), table_name='justice_policy_change_log')
    op.drop_table('justice_policy_change_log')
    op.drop_index(op.f('ix_telemetry_events_created_at'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_session_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_user_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_treasury_flows_agency_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_app'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_kind'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_performer_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_reference_id'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_ts'), table_name='treasury_flows')
    op.drop_index(op.f('ix_treasury_flows_user_id'), table_name='treasury_flows')
    op.drop_table('treasury_flows')
    # Create ncr_market_state table
    op.create_table('ncr_market_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_price_try', sa.Float(), nullable=False),
    sa.Column('last_price_try', sa.Float(), nullable=False),
    sa.Column('ema_coverage', sa.Float(), nullable=False),
    sa.Column('ema_flow_index', sa.Float(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_flows',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('app', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('net_to_performer', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('growth_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('performer_pool_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('dev_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('burn_amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('treasury_flows_agency_id_fkey')),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], name=op.f('treasury_flows_performer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('treasury_flows_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('treasury_flows_pkey'))
    )
    op.create_index(op.f('ix_treasury_flows_user_id'), 'treasury_flows', ['user_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_ts'), 'treasury_flows', ['ts'], unique=False)
    op.create_index(op.f('ix_treasury_flows_reference_id'), 'treasury_flows', ['reference_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_performer_id'), 'treasury_flows', ['performer_id'], unique=False)
    op.create_index(op.f('ix_treasury_flows_kind'), 'treasury_flows', ['kind'], unique=False)
    op.create_index(op.f('ix_treasury_flows_app'), 'treasury_flows', ['app'], unique=False)
    op.create_index(op.f('ix_treasury_flows_agency_id'), 'treasury_flows', ['agency_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_events_pkey'))
    )
    op.create_index(op.f('ix_telemetry_events_user_id'), 'telemetry_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_session_id'), 'telemetry_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event'), 'telemetry_events', ['event'], unique=False)
    op.create_index(op.f('ix_telemetry_events_created_at'), 'telemetry_events', ['created_at'], unique=False)
    op.create_table('justice_policy_change_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('onchain_tx', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('justice_policy_change_log_pkey'))
    )
    op.create_index(op.f('ix_justice_policy_change_log_policy_version'), 'justice_policy_change_log', ['policy_version'], unique=False)
    op.create_index(op.f('ix_justice_policy_change_log_created_at'), 'justice_policy_change_log', ['created_at'], unique=False)
    op.create_table('justice_policy_params',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decay_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_eko', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_com', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_sys', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_trust', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_soft_flag', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_probation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_restricted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold_lockdown', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('onchain_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onchain_block', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('onchain_tx', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity_multiplier', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('justice_policy_params_pkey'))
    )
    op.create_index(op.f('ix_justice_policy_params_version'), 'justice_policy_params', ['version'], unique=False)
    op.create_index(op.f('ix_justice_policy_params_active'), 'justice_policy_params', ['active'], unique=False)
    op.create_table('system_accounts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_type', postgresql.ENUM('USER', 'PERFORMER', 'AGENCY_TREASURY', 'STATE_TREASURY', 'POOL_GROWTH', 'POOL_PERFORMER', 'POOL_DEV', 'POOL_BURN', name='systemaccounttype'), autoincrement=False, nullable=False),
    sa.Column('wallet_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('system_accounts_agency_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['accounts.id'], name=op.f('system_accounts_wallet_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_accounts_pkey'))
    )
    op.create_index(op.f('ix_system_accounts_wallet_account_id'), 'system_accounts', ['wallet_account_id'], unique=True)
    op.create_index(op.f('ix_system_accounts_agency_id'), 'system_accounts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_system_accounts_account_type'), 'system_accounts', ['account_type'], unique=False)
    # ### end Alembic commands ###

